services:
    dcms.test:
        build:
            context: ./docker/7.4
            dockerfile: Dockerfile
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - '.:/var/www/html'
        networks:
            - dcms
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - dcms-mysql:/var/lib/mysql
        networks:
            - dcms
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '${PHPMYADMIN_PORT:-81}:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - mysql
        networks:
            - dcms
networks:
    dcms:
        driver: bridge
volumes:
    dcms-mysql:
        driver: local